import type { AllowedAssetType, RejectedAssetType } from '../config/constants';

/** Union of every asset-type tag GMGN can report — allowed and rejected. */
export type AssetType = AllowedAssetType | RejectedAssetType;

/**
 * A single token surfaced by discovery, normalized into the shape every
 * downstream module (filters/pools/strategies/capital) consumes. This is
 * the ONLY place that knows about GMGN's raw response shape — everything
 * past `discovery/` deals exclusively with `CandidateToken`.
 */
export interface CandidateToken {
  /** EVM address on Robinhood Chain. */
  address: string;
  chainId: number;
  symbol: string;
  name: string;
  assetType: AssetType;
  marketCapUsd: number;
  /** Volume over the discovery timeframe window (6H), in USD. */
  volumeUsd: number;
  /** All-time total fee generated by the token's pool(s), in ETH, per GMGN. */
  totalFeeEth: number;
  /** Epoch ms token creation/listing time, as reported by GMGN. */
  createdAt: number;
  /**
   * Combined share held by the top 10 non-LP/non-burn wallets, as a 0..1
   * fraction (0.4 = 40%). Taken directly from GMGN — never computed via a
   * separate on-chain query, per spec.
   */
  top10HolderConcentrationPct: number;
  /** 1-based position in the GMGN Top-10 (6H) ranking for this cycle. */
  rank: number;
  /** Epoch ms when this discovery cycle fetched the token. */
  discoveredAt: number;
  source: 'GMGN';
  /** Original provider payload, kept only for debugging/audit — never read by filters/strategy logic. */
  raw?: unknown;
}
